### ISSUE TITLE
List not filled on first app run after fresh install

### ISSUE THREAD

**Issue by LoLei** [LoLei/sw-ss16#15]
Steps to reproduce:
- Uninstall app
- Run from Android Studio → app is installed
- **List not filled**
- Open Navdrawer, switch to settings activity, switch back to main activity
- Now list is filled

Does not happen if you had the app already installed.

**Comment by LoLei** [comment]
Related to #14

**Comment by d4bandel** [comment]
fixed with #20

**Comment by d4bandel** [comment]
Still happening as volley is asynchronous and the list will be setup, when the data is not already here -> maybe use synchronous task when first retrieving, as for refresh button, so we can use a loader -> have to look into this

**Comment by codecreativity** [comment]
maybe merge conflicts if started before merging #28

**Comment by codecreativity** [comment]
for sure merge conflicts with #28

**Comment by d4bandel** [comment]
Currently it's that after fresh install, there is no list, but going to settings and back to Favorite StudyRooms, the items are there.
Maybe update list instantly after everything is put into internal sqliteDb. With a toast Notification after fresh install, that it syncs in backrgound and the Rooms will show up shortly or something like that.
