### ISSUE TITLE
Images not working properly

### ISSUE THREAD

**Issue by codecreativity** [LoLei/sw-ss16#21]
Current fix: Always get images from remote server.

Desired solution:
When LCs synced, download images from provided URL and store them to "Internal Storage".
Then Store path to local images in local DB.

When needed, load images from internal storage to ImageView

**Comment by LoLei** [comment]
Current workaround: Store image URL in remote and local database, load images via URL in app.

Works fine as long as user has an internet connection (which they will probably have when they are on campus), and the images are cached without an internet connection as well for some time.

We can also easily add new images when new LCs are added via the remote database.
