### ISSUE TITLE
fix database connections

### ISSUE THREAD

**Issue by codecreativity** [LoLei/sw-ss16#36]
A SQLiteConnection object for database '+data+data+com_sw_ss16_lc_app+databases+Predictr_Database' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

**Comment by codecreativity** [comment]
nice labeling

**Comment by LoLei** [comment]
We need to close the database each time `new Database` is called apparently, the error message still shows up.
